stream {
    map $ssl_preread_server_name $backend {
        bl.hotvds.com  127.0.0.1:8444;
        po.hotvds.com  127.0.0.1:8445;
        pr.hotvds.com  127.0.0.1:8446;
        dev.hotvds.com  127.0.0.1:8443;
        hotvds.com  127.0.0.1:8443;
        default       127.0.0.1:8444;
    }

    server {
        listen 443;
        proxy_pass $backend;
        ssl_preread on;
    }
}
